--liquibase formatted sql

--changeset polina.petrushina:create-transport-tables runOnChange:false runAlways:false dbms:postgresql
CREATE TABLE transport
(
    id              int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type            varchar(150)                         NOT NULL,
    subtype         varchar(150)                         NOT NULL,
    model           varchar(150)                         NOT NULL,
    number          varchar(150)                         NOT NULL,
    is_available    boolean                              NOT NULL,
    CONSTRAINT transport_pk PRIMARY KEY (id)
);

COMMENT ON TABLE transport IS 'Таблица траснпортов';
COMMENT ON COLUMN transport.id IS 'Идентификатор транспорта';
COMMENT ON COLUMN transport.type IS 'Тип транспорта';
COMMENT ON COLUMN transport.subtype IS 'Подтип транспорта';
COMMENT ON COLUMN transport.model IS 'Модель транспортп';
COMMENT ON COLUMN transport.number IS 'Номер транспорта';
COMMENT ON COLUMN transport.is_available IS 'Доступен ли транспорт';

CREATE TABLE transport_price
(
    transport_price_id           int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    price        numeric                              NOT NULL,
    is_actual    boolean DEFAULT false,
    transport_id int                                  NOT NULL REFERENCES transport (id) ON DELETE CASCADE,
    CONSTRAINT transport_price_pk PRIMARY KEY (transport_price_id)
);

COMMENT ON TABLE transport_price IS 'Таблица цен на аренду транспорта';
COMMENT ON COLUMN transport_price.transport_price_id   IS 'Идентификатор цены на аренду транспорта';
COMMENT ON COLUMN transport_price.price IS 'Цена на аренду транспорта';
COMMENT ON COLUMN transport_price.is_actual IS 'Актуальность цены';
COMMENT ON COLUMN transport_price.transport_id IS 'Идентификатор транспорта';
