--liquibase formatted sql

--changeset polina.petrushina:create-extra-service-tables runOnChange:false runAlways:false dbms:postgresql
CREATE TABLE extra_service
(
    id                 int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    extra_service_name varchar NOT NULL,
    CONSTRAINT extra_service_pk PRIMARY KEY (id)
);

COMMENT ON TABLE extra_service IS 'Таблица дополнительных услуг';
COMMENT ON COLUMN extra_service.id IS 'Идентификатор дополнительной услуги';
COMMENT ON COLUMN extra_service.extra_service_name IS 'Наименование дополнительной услуги';

CREATE TABLE extra_service_price
(
    id               int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    price            numeric NOT NULL,
    is_actual        boolean DEFAULT true,
    extra_service_id int     NOT NULL REFERENCES extra_service (id) ON DELETE CASCADE,
    CONSTRAINT extra_service_price_pk PRIMARY KEY (id)
);

COMMENT ON TABLE extra_service_price IS 'Таблица стоимости дополнительных услуг';
COMMENT ON COLUMN extra_service_price.id IS 'Идентификатор стоимости услуги';
COMMENT ON COLUMN extra_service_price.price IS 'Стоимость услуги';
COMMENT ON COLUMN extra_service_price.is_actual IS 'Актуальность стоимости';
COMMENT ON COLUMN extra_service_price.extra_service_id IS 'Идентификатор услуги';