--liquibase formatted sql

--changeset polina.petrushina:create-booking-tables runOnChange:false runAlways:false dbms:postgresql
CREATE TABLE booking
(
    id                    int GENERATED BY DEFAULT AS IDENTITY        NOT NULL,
    creation_date         timestamp                                   NOT NULL,
    edit_date             timestamp                                   NOT NULL,
    last_edit_admin       varchar                                     NOT NULL,
    pick_up_address       varchar(150)                                NOT NULL,
    drop_of_address       varchar(150)                                NOT NULL,
    start_rent_date       timestamp                                   NOT NULL,
    scheduled_return_date timestamp                                   NOT NULL,
    actual_return_date    timestamp,
    status                varchar                                     NOT NULL,
    user_id               int REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    transport_id          int REFERENCES transport(id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT booking_pk PRIMARY KEY (id)
);

COMMENT ON TABLE booking IS 'Таблица бронирований';
COMMENT ON COLUMN booking.id IS 'Идентификатор бронирования';
COMMENT ON COLUMN booking.creation_date IS 'Дата и время создания бронирования';
COMMENT ON COLUMN booking.edit_date IS 'Дата и время редактирования бронирования';
COMMENT ON COLUMN booking.last_edit_admin IS 'Администратор, вносивший последние изменения';
COMMENT ON COLUMN booking.pick_up_address IS 'Адрес посадки';
COMMENT ON COLUMN booking.drop_of_address IS 'Адрес высадки';
COMMENT ON COLUMN booking.start_rent_date IS 'Дата начала аренды транспорта';
COMMENT ON COLUMN booking.scheduled_return_date IS 'Дата запланированного возврата транспорта';
COMMENT ON COLUMN booking.actual_return_date IS 'Дата возврата транспорта';
COMMENT ON COLUMN booking.status IS 'Статус бронирования';
COMMENT ON COLUMN booking.user_id IS 'Идентификатор пользователя, который создал бронирование';

CREATE TABLE booking_extra_service
(
    booking_id       int NOT NULL,
    extra_service_id int NOT NULL,
    CONSTRAINT booking_extra_service_pk PRIMARY KEY (booking_id, extra_service_id),
    CONSTRAINT fk_booking FOREIGN KEY (booking_id) REFERENCES booking (id) ON DELETE CASCADE,
    CONSTRAINT fk_extra_service FOREIGN KEY (extra_service_id) REFERENCES extra_service(extra_service_id) ON DELETE CASCADE
);
COMMENT ON TABLE booking_extra_service IS 'Таблица бронирований и дополнительных услуг';
COMMENT ON COLUMN booking_extra_service.booking_id IS 'Идентификатор бронирования';
COMMENT ON COLUMN booking_extra_service.extra_service_id IS 'Идентификатор дополнительной услуги';